### ISSUE TITLE
Fix docker log rotation bug

### ISSUE THREAD

**Issue by parithosh** [ethpandaops/ansible-collection-general#62]
We need to use the common log options instead of the log rotate role as from docker 23.x.x, the docker cli expects to be the sole owner of the docker logs file. If other processes touch the log file then the `truncate` options fail, i.e, `--tail=`.

Tracked here: https://github.com/docker/cli/issues/4008
older moby issue: https://github.com/moby/moby/issues/36853

We need to decide a proper path forward. Options:
- Use common log options and just rotate logs on docker containers, i.e:
```
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file
```
- Pin older version of docker

We additionally need to see if it makes sense to keep the logrotate role in light of this. Atleast we need to add a disclaimer so people don't inadvertently run into this issue.
